services:
  - type: web
    name: atomshop
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    branch: main
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: PAYMENT_MODE
        value: test
      - key: PANEL_API_URL
        value: https://panel.pepehost.pl
      - key: PANEL_SERVER_ID
        value: 4432ca12
      - key: PANEL_API_KEY
        sync: false
